"""
METHOD D1 (FROM SCRATCH) — Bounding Box Regression, No Pretrained Models
===========================================================================
CONSTRAINT: Only numpy, opencv, pandas. No torch/sklearn/pretrained weights.

WHAT THIS BUILDS, FROM ZERO:
    1. Anchor boxes         - generated by sliding a grid over the image
    2. Feature extraction   - hand-computed pixel statistics per anchor
                               (mean intensity, std dev, edge density via
                               Sobel, aspect ratio) -- NOT a pretrained CNN
    3. A neural network     - written with raw numpy: forward pass,
                               backward pass, gradient descent, ALL
                               derived and coded by hand (no autograd)
    4. Two loss functions   - Binary Cross-Entropy (objectness: is there
                               an object in this anchor?) and Smooth L1
                               (box regression: how to adjust the anchor
                               to fit the object)
    5. Non-Max Suppression  - written by hand, removes duplicate boxes
    6. Training data         - generated synthetically (random rectangles
                               on random backgrounds) since we have no
                               pretrained model and no labelled dataset
    7. cm conversion         - same scale-factor principle as every
                               other method in this project

WHY SYNTHETIC TRAINING DATA:
    A neural network needs labelled examples to learn "adjust this anchor
    by this much." With zero pretrained weights and zero external
    datasets allowed, the only way to train is to generate our own
    labelled data. This script draws random rectangles (simulating
    objects) at random positions/sizes on random backgrounds, and uses
    the KNOWN ground truth box as the training label. This lets the
    network learn genuine bounding-box regression from mathematical
    first principles.

    Once you have real labelled rice-grain images later, you swap the
    synthetic data generator for your real dataset -- the network,
    training loop, and math stay identical.

HOW TO RUN:
    # Train from scratch on synthetic data, then test on a real image:
    python method_d1_scratch.py --train --image your_photo.jpg --scale 0.05

    # Just run the synthetic demo end-to-end (train + test on synthetic):
    python method_d1_scratch.py --demo

    # Use a previously trained model (skips retraining):
    python method_d1_scratch.py --image your_photo.jpg --scale 0.05 \
        --load_weights weights.npz

    # Interactive reference scale + real image:
    python method_d1_scratch.py --image your_photo.jpg \
        --interactive_ref --ref_cm 21.0
"""

import cv2
import numpy as np
import pandas as pd
import argparse
import os
import math

np.random.seed(42)

# ============================================================================
# SECTION 1 — SYNTHETIC TRAINING DATA GENERATION
# ============================================================================

def make_textured_background(img_size):
    """
    Generate a wood-grain-like textured background: directional noise
    stripes. Real surfaces (wood, fabric, tile) have HIGH edge density
    everywhere -- the network must learn that edges alone don't mean
    'object'; only edges forming a coherent blob distinct from
    surrounding texture do.
    """
    base = np.random.randint(90, 180)
    img = np.full((img_size, img_size, 3), base, dtype=np.uint8)
    # Horizontal or vertical grain stripes
    vertical = np.random.rand() < 0.5
    n_stripes = np.random.randint(15, 40)
    for _ in range(n_stripes):
        pos = np.random.randint(0, img_size)
        thickness = np.random.randint(1, 4)
        shade = np.random.randint(-40, 40)
        color = np.clip(base + shade, 0, 255)
        if vertical:
            img[:, pos:pos+thickness] = color
        else:
            img[pos:pos+thickness, :] = color
    # Slight blur so stripes look organic, not hard-edged
    img = cv2.GaussianBlur(img, (3,3), 0)
    # Tint toward brown (wood-like) sometimes
    if np.random.rand() < 0.6:
        img = img.astype(np.int16)
        img[:,:,0] = np.clip(img[:,:,0]*0.6, 0, 255)   # less blue
        img[:,:,1] = np.clip(img[:,:,1]*0.8, 0, 255)   # less green
        img = img.astype(np.uint8)
    noise = np.random.randint(-8,8,img.shape,dtype=np.int16)
    img = np.clip(img.astype(np.int16)+noise,0,255).astype(np.uint8)
    return img


def generate_synthetic_sample(img_size=128, textured_bg_prob=0.7):
    """
    Create one synthetic training image: a random-colored rectangle
    (the 'object') on a background that is EITHER flat-color OR
    textured (wood-grain-like), so the classifier learns to
    distinguish real objects from textured surfaces. Returns the
    image and the ground-truth box [x1,y1,x2,y2].
    """
    if np.random.rand() < textured_bg_prob:
        img = make_textured_background(img_size)
    else:
        bg_color = np.random.randint(150, 230, 3).tolist()
        img = np.full((img_size, img_size, 3), bg_color, dtype=np.uint8)

    # Random object box (width/height between 20% and 60% of image)
    w = np.random.randint(int(0.2*img_size), int(0.6*img_size))
    h = np.random.randint(int(0.2*img_size), int(0.6*img_size))
    x1 = np.random.randint(0, img_size - w)
    y1 = np.random.randint(0, img_size - h)
    x2, y2 = x1 + w, y1 + h

    obj_color = np.random.randint(20, 120, 3).tolist()
    shape = np.random.choice(['rect', 'ellipse'])
    if shape == 'rect':
        cv2.rectangle(img, (x1,y1), (x2,y2), obj_color, -1)
    else:
        cv2.ellipse(img, ((x1+x2)//2,(y1+y2)//2), (w//2,h//2),
                    0, 0, 360, obj_color, -1)

    # Add noise so features aren't trivially separable
    noise = np.random.randint(-10, 10, img.shape, dtype=np.int16)
    img = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)

    return img, np.array([x1, y1, x2, y2], dtype=np.float32)


def generate_dataset(n_samples=400, img_size=128):
    """Generate n synthetic (image, box) training pairs."""
    images, boxes = [], []
    for _ in range(n_samples):
        img, box = generate_synthetic_sample(img_size)
        images.append(img)
        boxes.append(box)
    return images, boxes


# ============================================================================
# SECTION 2 — ANCHOR BOXES (hand-built, no library)
# ============================================================================

def generate_anchors(img_size, stride=16, scales=(32,64), ratios=(0.5,1.0,2.0)):
    """
    Slide a grid of anchor boxes over the image.

    stride  : spacing between anchor centers (pixels)
    scales  : anchor box areas (as side length in px, roughly)
    ratios  : width:height ratios per scale

    Returns: (N,4) array of anchor boxes [x1,y1,x2,y2]
    """
    anchors = []
    for cy in range(stride//2, img_size, stride):
        for cx in range(stride//2, img_size, stride):
            for s in scales:
                for r in ratios:
                    w = s * math.sqrt(r)
                    h = s / math.sqrt(r)
                    x1 = cx - w/2
                    y1 = cy - h/2
                    x2 = cx + w/2
                    y2 = cy + h/2
                    anchors.append([x1,y1,x2,y2])
    anchors = np.array(anchors, dtype=np.float32)
    # Clip to image bounds
    anchors[:,0] = np.clip(anchors[:,0], 0, img_size-1)
    anchors[:,1] = np.clip(anchors[:,1], 0, img_size-1)
    anchors[:,2] = np.clip(anchors[:,2], 0, img_size-1)
    anchors[:,3] = np.clip(anchors[:,3], 0, img_size-1)
    return anchors


def box_iou(boxes1, boxes2):
    """
    Vectorized IoU between two sets of boxes.
    boxes1: (N,4)  boxes2: (M,4)  -> returns (N,M) IoU matrix
    """
    N, M = len(boxes1), len(boxes2)
    iou = np.zeros((N, M), dtype=np.float32)
    for i in range(N):
        x1 = np.maximum(boxes1[i,0], boxes2[:,0])
        y1 = np.maximum(boxes1[i,1], boxes2[:,1])
        x2 = np.minimum(boxes1[i,2], boxes2[:,2])
        y2 = np.minimum(boxes1[i,3], boxes2[:,3])
        inter = np.maximum(0, x2-x1) * np.maximum(0, y2-y1)
        area1 = (boxes1[i,2]-boxes1[i,0]) * (boxes1[i,3]-boxes1[i,1])
        area2 = (boxes2[:,2]-boxes2[:,0]) * (boxes2[:,3]-boxes2[:,1])
        union = area1 + area2 - inter
        iou[i] = inter / (union + 1e-7)
    return iou


def encode_box_targets(anchors, gt_box):
    """
    Convert ground-truth box into regression targets (tx,ty,tw,th)
    relative to each anchor -- exactly the anchor-offset math from
    Faster R-CNN theory, derived here by hand.
    """
    ax1,ay1,ax2,ay2 = anchors[:,0],anchors[:,1],anchors[:,2],anchors[:,3]
    aw = ax2-ax1; ah = ay2-ay1
    acx = ax1 + aw/2; acy = ay1 + ah/2

    gx1,gy1,gx2,gy2 = gt_box
    gw = gx2-gx1; gh = gy2-gy1
    gcx = gx1 + gw/2; gcy = gy1 + gh/2

    tx = (gcx - acx) / (aw + 1e-7)
    ty = (gcy - acy) / (ah + 1e-7)
    tw = np.log((gw + 1e-7) / (aw + 1e-7))
    th = np.log((gh + 1e-7) / (ah + 1e-7))
    return np.stack([tx,ty,tw,th], axis=1)


def decode_box(anchor, offsets):
    """Inverse of encode_box_targets -- turn (tx,ty,tw,th) back into a box."""
    ax1,ay1,ax2,ay2 = anchor
    aw, ah = ax2-ax1, ay2-ay1
    acx, acy = ax1+aw/2, ay1+ah/2

    tx,ty,tw,th = offsets
    pcx = tx*aw + acx
    pcy = ty*ah + acy
    pw  = aw * math.exp(np.clip(tw, -4, 4))
    ph  = ah * math.exp(np.clip(th, -4, 4))

    return np.array([pcx-pw/2, pcy-ph/2, pcx+pw/2, pcy+ph/2])


# ============================================================================
# SECTION 3 — HAND-CRAFTED FEATURE EXTRACTION (no pretrained CNN)
# ============================================================================

def extract_features(image, box):
    """
    Compute a feature vector for the image region inside `box`,
    using only basic pixel statistics and OpenCV's classical (non-ML)
    operators -- Sobel gradients, standard deviation, etc.

    This replaces the "backbone CNN" of a real detector. It is far
    weaker than a learned CNN feature extractor, but it is built
    entirely from first principles as required.
    """
    h, w = image.shape[:2]
    x1,y1,x2,y2 = [int(max(0,min(v, w if i%2==0 else h)))
                   for i,v in enumerate(box)]
    x1,x2 = sorted([max(0,min(x1,w-1)), max(0,min(x2,w-1))])
    y1,y2 = sorted([max(0,min(y1,h-1)), max(0,min(y2,h-1))])
    if x2<=x1: x2 = x1+1
    if y2<=y1: y2 = y1+1

    patch = image[y1:y2, x1:x2]
    if patch.size == 0:
        return np.zeros(10, dtype=np.float32)

    gray = cv2.cvtColor(patch, cv2.COLOR_BGR2GRAY).astype(np.float32)

    mean_i  = gray.mean()
    std_i   = gray.std()

    sobel_x = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    grad_mag = np.sqrt(sobel_x**2 + sobel_y**2)
    edge_density = grad_mag.mean()
    edge_std     = grad_mag.std()

    # Color channel means (BGR)
    b_mean, g_mean, r_mean = patch[:,:,0].mean(), patch[:,:,1].mean(), patch[:,:,2].mean()

    box_w = x2-x1
    box_h = y2-y1
    aspect = box_w / (box_h + 1e-7)
    rel_area = (box_w*box_h) / (w*h)

    feat = np.array([
        mean_i/255.0, std_i/255.0,
        edge_density/255.0, edge_std/255.0,
        b_mean/255.0, g_mean/255.0, r_mean/255.0,
        aspect/5.0, rel_area,
        1.0   # bias-friendly constant feature
    ], dtype=np.float32)
    return feat


# ============================================================================
# SECTION 4 — NEURAL NETWORK, FULLY FROM SCRATCH (numpy only)
# ============================================================================

class TinyDetectorNet:
    """
    Small MLP trained from scratch with manual forward/backward passes.

    Architecture:
        Input (10 features)
          -> Dense(32) + ReLU
          -> Dense(16) + ReLU
          -> TWO heads:
               objectness head -> Dense(1) + Sigmoid   (binary cls)
               box head        -> Dense(4)             (regression: tx,ty,tw,th)

    Every gradient below is derived by hand via the chain rule --
    no autograd, no external ML library.
    """

    def __init__(self, in_dim=10, h1=32, h2=16, lr=0.01):
        rng = np.random.RandomState(42)
        self.lr = lr
        # Xavier-ish init
        self.W1 = rng.randn(in_dim, h1) * math.sqrt(2.0/in_dim)
        self.b1 = np.zeros(h1)
        self.W2 = rng.randn(h1, h2) * math.sqrt(2.0/h1)
        self.b2 = np.zeros(h2)
        self.W_cls = rng.randn(h2, 1) * math.sqrt(2.0/h2)
        self.b_cls = np.zeros(1)
        self.W_box = rng.randn(h2, 4) * math.sqrt(1.0/h2)
        self.b_box = np.zeros(4)

    @staticmethod
    def relu(x):
        return np.maximum(0, x)

    @staticmethod
    def relu_grad(x):
        return (x > 0).astype(np.float32)

    @staticmethod
    def sigmoid(x):
        x = np.clip(x, -30, 30)
        return 1.0 / (1.0 + np.exp(-x))

    def forward(self, X):
        """X: (N, in_dim) -> returns cls_prob (N,1), box_pred (N,4), cache for backward"""
        z1 = X @ self.W1 + self.b1
        a1 = self.relu(z1)
        z2 = a1 @ self.W2 + self.b2
        a2 = self.relu(z2)

        cls_logit = a2 @ self.W_cls + self.b_cls
        cls_prob  = self.sigmoid(cls_logit)

        box_pred  = a2 @ self.W_box + self.b_box

        cache = (X, z1, a1, z2, a2, cls_logit)
        return cls_prob, box_pred, cache

    def compute_loss(self, cls_prob, cls_target, box_pred, box_target, is_positive):
        """
        cls_target  : (N,1) 1 if object, 0 if background
        box_target  : (N,4) regression targets, only meaningful where is_positive
        is_positive : (N,) boolean mask -- box loss only applies to positive anchors
        """
        eps = 1e-7
        # Binary cross-entropy for objectness
        bce = -(cls_target*np.log(cls_prob+eps) +
                (1-cls_target)*np.log(1-cls_prob+eps))
        cls_loss = bce.mean()

        # Smooth L1 for box regression -- ONLY on positive anchors
        diff = box_pred - box_target
        abs_diff = np.abs(diff)
        smooth = np.where(abs_diff < 1, 0.5*diff**2, abs_diff - 0.5)
        if is_positive.sum() > 0:
            box_loss = smooth[is_positive].sum() / max(1, is_positive.sum())
        else:
            box_loss = 0.0

        total = cls_loss + box_loss
        return total, cls_loss, box_loss

    def backward(self, cache, cls_prob, cls_target, box_pred, box_target, is_positive):
        X, z1, a1, z2, a2, cls_logit = cache
        N = X.shape[0]

        # ---- Gradient of BCE w.r.t. cls_logit (sigmoid+BCE combined = simple) ----
        d_cls_logit = (cls_prob - cls_target) / N            # (N,1)

        # ---- Gradient of Smooth L1 w.r.t. box_pred (masked to positives) ----
        diff = box_pred - box_target
        d_smooth = np.where(np.abs(diff) < 1, diff, np.sign(diff))
        mask = is_positive.reshape(-1,1).astype(np.float32)
        n_pos = max(1, is_positive.sum())
        d_box_pred = d_smooth * mask / n_pos                  # (N,4)

        # ---- Output layer grads ----
        dW_cls = a2.T @ d_cls_logit
        db_cls = d_cls_logit.sum(axis=0)
        dW_box = a2.T @ d_box_pred
        db_box = d_box_pred.sum(axis=0)

        # ---- Backprop into shared trunk (a2) ----
        d_a2 = d_cls_logit @ self.W_cls.T + d_box_pred @ self.W_box.T
        d_z2 = d_a2 * self.relu_grad(z2)

        dW2 = a1.T @ d_z2
        db2 = d_z2.sum(axis=0)

        d_a1 = d_z2 @ self.W2.T
        d_z1 = d_a1 * self.relu_grad(z1)

        dW1 = X.T @ d_z1
        db1 = d_z1.sum(axis=0)

        # ---- Gradient descent update ----
        self.W_cls -= self.lr * dW_cls
        self.b_cls -= self.lr * db_cls
        self.W_box -= self.lr * dW_box
        self.b_box -= self.lr * db_box
        self.W2    -= self.lr * dW2
        self.b2    -= self.lr * db2
        self.W1    -= self.lr * dW1
        self.b1    -= self.lr * db1

    def save(self, path):
        np.savez(path, W1=self.W1, b1=self.b1, W2=self.W2, b2=self.b2,
                 W_cls=self.W_cls, b_cls=self.b_cls,
                 W_box=self.W_box, b_box=self.b_box)
        print(f"  Weights saved -> {path}")

    def load(self, path):
        d = np.load(path)
        self.W1, self.b1 = d['W1'], d['b1']
        self.W2, self.b2 = d['W2'], d['b2']
        self.W_cls, self.b_cls = d['W_cls'], d['b_cls']
        self.W_box, self.b_box = d['W_box'], d['b_box']
        print(f"  Weights loaded from {path}")


# ============================================================================
# SECTION 5 — TRAINING LOOP
# ============================================================================

def train_network(n_samples=400, img_size=128, epochs=60, lr=0.05,
                  pos_iou_thresh=0.5, neg_iou_thresh=0.2):
    """
    Full training loop: generate synthetic data, build anchors, label
    them by IoU with ground truth, extract features, train the MLP
    with manual gradient descent.
    """
    print("\n  Generating synthetic training data...")
    images, gt_boxes = generate_dataset(n_samples, img_size)

    anchors = generate_anchors(img_size, stride=16, scales=(32,56), ratios=(0.5,1.0,2.0))
    print(f"  Anchors per image: {len(anchors)}")

    net = TinyDetectorNet(in_dim=10, h1=32, h2=16, lr=lr)

    print(f"  Training for {epochs} epochs on {n_samples} synthetic images...\n")

    for epoch in range(epochs):
        epoch_loss, epoch_cls, epoch_box = 0.0, 0.0, 0.0
        n_batches = 0

        for img, gt_box in zip(images, gt_boxes):
            ious = box_iou(anchors, gt_box.reshape(1,4)).flatten()

            is_positive = ious >= pos_iou_thresh
            is_negative = ious < neg_iou_thresh

            # Balance: sample a subset of negatives (there are far more
            # negative anchors than positive -- classic class imbalance)
            pos_idx = np.where(is_positive)[0]
            neg_idx = np.where(is_negative)[0]
            n_pos = len(pos_idx)
            n_neg = min(len(neg_idx), max(8, n_pos*3))
            if n_neg > 0:
                neg_idx = np.random.choice(neg_idx, n_neg, replace=False)

            if n_pos == 0:
                # Force the single best-IoU anchor to be positive
                best = np.argmax(ious)
                pos_idx = np.array([best])
                is_positive = np.zeros(len(anchors), dtype=bool)
                is_positive[best] = True

            sample_idx = np.concatenate([pos_idx, neg_idx]).astype(int)
            if len(sample_idx) == 0:
                continue

            sample_anchors = anchors[sample_idx]
            sample_is_pos  = is_positive[sample_idx]

            # Features per sampled anchor
            X = np.stack([extract_features(img, a) for a in sample_anchors])

            cls_target = sample_is_pos.reshape(-1,1).astype(np.float32)
            box_target = np.zeros((len(sample_idx), 4), dtype=np.float32)
            if sample_is_pos.sum() > 0:
                pos_anchors_full = sample_anchors[sample_is_pos]
                box_target[sample_is_pos] = encode_box_targets(
                    pos_anchors_full, gt_box)

            cls_prob, box_pred, cache = net.forward(X)
            loss, cls_l, box_l = net.compute_loss(
                cls_prob, cls_target, box_pred, box_target, sample_is_pos)
            net.backward(cache, cls_prob, cls_target, box_pred,
                        box_target, sample_is_pos)

            epoch_loss += loss; epoch_cls += cls_l; epoch_box += box_l
            n_batches += 1

        if (epoch+1) % 10 == 0 or epoch == 0:
            print(f"  Epoch {epoch+1:3d}/{epochs}  "
                  f"loss={epoch_loss/n_batches:.4f}  "
                  f"cls={epoch_cls/n_batches:.4f}  "
                  f"box={epoch_box/n_batches:.4f}")

    print("\n  Training complete.")
    return net, anchors


# ============================================================================
# SECTION 6 — NON-MAX SUPPRESSION (hand-written)
# ============================================================================

def mine_hard_negatives(net, anchors, bg_image, img_size=128,
                        conf_threshold=0.5, max_negatives=60):
    """
    HARD NEGATIVE MINING.

    Run the current network over a real background-only image (no
    target object present -- e.g. a photo of just your table/wood
    surface). Any anchor the network classifies as "object" here is,
    by definition, a FALSE POSITIVE. Collect these as explicit hard
    negative examples and feed them back into training.

    This is the classical fix (pre-dating deep learning, used in
    Viola-Jones and HOG+SVM detectors) for a classifier that has
    learned a spurious signal -- exactly what happened here, where
    edge density from wood grain was mistaken for "object present."
    """
    resized = cv2.resize(bg_image, (img_size, img_size))
    X = np.stack([extract_features(resized, a) for a in anchors])
    cls_prob, _, _ = net.forward(X)
    cls_prob = cls_prob.flatten()

    false_pos_idx = np.where(cls_prob >= conf_threshold)[0]
    print(f"  Hard negatives found in background image: {len(false_pos_idx)}")

    if len(false_pos_idx) > max_negatives:
        false_pos_idx = np.random.choice(false_pos_idx, max_negatives,
                                         replace=False)

    hard_neg_anchors = anchors[false_pos_idx]
    if len(hard_neg_anchors) == 0:
        return np.zeros((0, 10), dtype=np.float32)
    hard_neg_features = np.stack(
        [extract_features(resized, a) for a in hard_neg_anchors])
    return hard_neg_features


def train_with_hard_negatives(net, anchors, hard_neg_features,
                              epochs=20, lr=0.02):
    """
    Fine-tune the network using ONLY hard negative examples --
    explicitly pushing their objectness score toward 0. This directly
    corrects the false-positive behaviour without needing new
    positive examples.
    """
    if len(hard_neg_features) == 0:
        print("  No hard negatives to train on -- skipping.")
        return net

    net.lr = lr
    print(f"\n  Fine-tuning on {len(hard_neg_features)} hard negatives "
          f"for {epochs} epochs...")

    cls_target = np.zeros((len(hard_neg_features), 1), dtype=np.float32)
    box_target = np.zeros((len(hard_neg_features), 4), dtype=np.float32)
    is_positive = np.zeros(len(hard_neg_features), dtype=bool)

    for epoch in range(epochs):
        cls_prob, box_pred, cache = net.forward(hard_neg_features)
        loss, cls_l, box_l = net.compute_loss(
            cls_prob, cls_target, box_pred, box_target, is_positive)
        net.backward(cache, cls_prob, cls_target, box_pred,
                     box_target, is_positive)
        if (epoch+1) % 5 == 0:
            print(f"    Epoch {epoch+1}/{epochs}  hard-neg loss={loss:.4f}  "
                  f"mean confidence now={cls_prob.mean():.4f}")

    print("  Hard negative fine-tuning complete.")
    return net


def non_max_suppression(boxes, scores, iou_threshold=0.4):
    """Standard NMS, implemented from scratch. Returns indices to keep."""
    if len(boxes) == 0:
        return []
    order = np.argsort(scores)[::-1]
    keep = []
    while len(order) > 0:
        i = order[0]
        keep.append(i)
        if len(order) == 1:
            break
        rest = order[1:]
        ious = box_iou(boxes[i:i+1], boxes[rest]).flatten()
        order = rest[ious < iou_threshold]
    return keep


def propose_regions_by_contour(image, min_area_frac=0.01, max_area_frac=0.5):
    """
    CLASSICAL region proposal (like the original R-CNN, before Faster
    R-CNN added a learned RPN). Instead of blindly classifying a dense
    grid of thousands of anchors everywhere, use classical segmentation
    to find the small number of regions that actually LOOK like a
    distinct object -- then only classify those.

    This directly fixes the false-positive-everywhere failure: there
    is no dense grid left for a weak classifier to misfire on.
    """
    h, w = image.shape[:2]
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)

    # Otsu automatic thresholding -- try both polarities, keep whichever
    # produces sane-looking connected components
    _, th1 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    _, th2 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

    proposals = []
    for th in (th1, th2):
        kernel = np.ones((5,5), np.uint8)
        clean = cv2.morphologyEx(th, cv2.MORPH_CLOSE, kernel, iterations=2)
        clean = cv2.morphologyEx(clean, cv2.MORPH_OPEN, kernel, iterations=1)

        contours, _ = cv2.findContours(clean, cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_SIMPLE)
        img_area = h * w
        for c in contours:
            area = cv2.contourArea(c)
            frac = area / img_area
            if min_area_frac <= frac <= max_area_frac:
                x,y,bw,bh = cv2.boundingRect(c)
                # Reject boxes touching image border (likely surface/shadow)
                margin = 3
                if x<margin or y<margin or x+bw>w-margin or y+bh>h-margin:
                    continue
                proposals.append([x, y, x+bw, y+bh])

    if not proposals:
        return np.zeros((0,4), dtype=np.float32)

    proposals = np.array(proposals, dtype=np.float32)
    # De-duplicate near-identical proposals from the two threshold polarities
    keep = non_max_suppression(proposals, np.ones(len(proposals)), 0.6)
    return proposals[keep]


def detect_and_measure_hybrid(net, image, scale_cm_per_px,
                              conf_threshold=0.5):
    """
    HYBRID pipeline: classical contour proposals (few, precise) +
    learned classifier/regressor (scores and refines each proposal).

    Use this instead of detect_and_measure() for single/few-object
    scenes -- it is far more robust than dense anchor sliding-window
    search with a weak hand-crafted-feature classifier.
    """
    proposals = propose_regions_by_contour(image)
    print(f"  Contour-based candidate regions found: {len(proposals)}")

    if len(proposals) == 0:
        return image.copy(), pd.DataFrame(
            columns=["x1","y1","x2","y2","width_px","height_px",
                     "width_cm","height_cm","area_cm2","confidence"])

    X = np.stack([extract_features(image, box) for box in proposals])
    cls_prob, box_pred, _ = net.forward(X)
    cls_prob = cls_prob.flatten()

    print(f"  Candidate confidences: "
          f"{[f'{s:.2f}' for s in sorted(cls_prob, reverse=True)]}")

    keep_mask = cls_prob >= conf_threshold
    if keep_mask.sum() == 0:
        print(f"  No candidates above confidence {conf_threshold}. "
              f"Showing all candidates with raw scores instead.")
        keep_mask = np.ones(len(proposals), dtype=bool)

    final_boxes  = proposals[keep_mask]
    final_scores = cls_prob[keep_mask]

    vis = image.copy()
    rows = []
    for box, score in zip(final_boxes, final_scores):
        x1,y1,x2,y2 = box
        w_px, h_px = x2-x1, y2-y1
        w_cm, h_cm = w_px*scale_cm_per_px, h_px*scale_cm_per_px

        cv2.rectangle(vis, (int(x1),int(y1)), (int(x2),int(y2)), (0,200,80), 2)
        put_text(vis, f"{score:.2f} | {w_cm:.1f}x{h_cm:.1f}cm",
                 (int(x1), int(max(15,y1-8))), (0,200,80), 0.5)

        rows.append({
            "x1":x1,"y1":y1,"x2":x2,"y2":y2,
            "width_px":w_px, "height_px":h_px,
            "width_cm":w_cm, "height_cm":h_cm,
            "area_cm2":w_cm*h_cm, "confidence":score
        })

    return vis, pd.DataFrame(rows)


def propose_regions_two_stage(image, min_area_frac=0.001, max_area_frac=0.3):
    """
    TWO-STAGE region proposal, built for the real use case: an object
    placed ON a reference surface (A4 paper, cutting board, etc.)
    which itself sits on a textured background (wood table).

    A single global threshold fails here because the object is a
    *hole* inside the paper's contour, invisible to RETR_EXTERNAL.

    Stage 1: find the paper/reference region (large, bright, roughly
             rectangular blob against the background)
    Stage 2: search ONLY inside that region for the object (which is
             darker/different from the paper it sits on)

    This mirrors exactly how you will use the pipeline in practice --
    object always placed on a known reference sheet.
    """
    h, w = image.shape[:2]
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)

    # ---- Stage 1: find the paper/reference region ----
    _, bright_mask = cv2.threshold(blur, 0, 255,
                                    cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    kernel = np.ones((9,9), np.uint8)
    bright_clean = cv2.morphologyEx(bright_mask, cv2.MORPH_CLOSE, kernel, 2)
    contours, _ = cv2.findContours(bright_clean, cv2.RETR_EXTERNAL,
                                    cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return np.zeros((0,4), dtype=np.float32), None

    paper_contour = max(contours, key=cv2.contourArea)
    px, py, pw, ph = cv2.boundingRect(paper_contour)
    paper_box = np.array([px, py, px+pw, py+ph], dtype=np.float32)

    # Reject if "paper" region is basically the whole image (bad threshold)
    if (pw*ph) / (w*h) > 0.85:
        paper_box = None

    # ---- Stage 2: search for object INSIDE the paper region ----
    if paper_box is not None:
        pad = 5
        rx1 = max(0, px+pad); ry1 = max(0, py+pad)
        rx2 = min(w, px+pw-pad); ry2 = min(h, py+ph-pad)
        roi = image[ry1:ry2, rx1:rx2]
    else:
        rx1, ry1 = 0, 0
        roi = image

    if roi.size == 0:
        return np.zeros((0,4), dtype=np.float32), paper_box

    roi_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    roi_blur = cv2.GaussianBlur(roi_gray, (5,5), 0)
    # Object should be darker than the (bright) paper it sits on
    _, obj_mask = cv2.threshold(roi_blur, 0, 255,
                                 cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
    kernel2 = np.ones((5,5), np.uint8)
    obj_clean = cv2.morphologyEx(obj_mask, cv2.MORPH_CLOSE, kernel2, 2)
    obj_clean = cv2.morphologyEx(obj_clean, cv2.MORPH_OPEN, kernel2, 1)

    obj_contours, _ = cv2.findContours(obj_clean, cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_SIMPLE)

    roi_area = roi.shape[0]*roi.shape[1]
    proposals = []
    for c in obj_contours:
        area = cv2.contourArea(c)
        frac = area / roi_area
        if min_area_frac <= frac <= max_area_frac:
            ox,oy,ow,oh = cv2.boundingRect(c)
            proposals.append([rx1+ox, ry1+oy, rx1+ox+ow, ry1+oy+oh])

    proposals = np.array(proposals) if proposals else np.zeros((0,4))
    if len(proposals) > 0:
        keep = non_max_suppression(proposals, np.ones(len(proposals)), 0.5)
        proposals_inside = proposals[keep]
    else:
        proposals_inside = np.zeros((0,4), dtype=np.float32)

    # ---- Stage 3: ALSO search OUTSIDE the paper (object may sit on
    #      the background surface, separate from the reference sheet).
    #      Search four independent strips (top/bottom/left/right of the
    #      paper) rather than masking the whole image -- masking with
    #      zeros corrupts Otsu's histogram statistics badly. ----
    proposals_outside = np.zeros((0,4), dtype=np.float32)
    if paper_box is not None:
        strips = []
        if py > 10:
            strips.append((0, 0, w, py))               # top strip
        if py+ph < h-10:
            strips.append((0, py+ph, w, h))             # bottom strip
        if px > 10:
            strips.append((0, 0, px, h))                # left strip
        if px+pw < w-10:
            strips.append((px+pw, 0, w, h))              # right strip

        out_props = []
        for (sx1, sy1, sx2, sy2) in strips:
            strip = image[sy1:sy2, sx1:sx2]
            if strip.size == 0:
                continue
            s_gray = cv2.cvtColor(strip, cv2.COLOR_BGR2GRAY)
            s_blur = cv2.GaussianBlur(s_gray, (5,5), 0)
            for mode in (cv2.THRESH_BINARY, cv2.THRESH_BINARY_INV):
                _, th = cv2.threshold(s_blur, 0, 255, mode+cv2.THRESH_OTSU)
                k = np.ones((7,7), np.uint8)
                clean = cv2.morphologyEx(th, cv2.MORPH_CLOSE, k, 2)
                clean = cv2.morphologyEx(clean, cv2.MORPH_OPEN, k, 1)
                cnts, _ = cv2.findContours(clean, cv2.RETR_EXTERNAL,
                                            cv2.CHAIN_APPROX_SIMPLE)
                strip_area = strip.shape[0]*strip.shape[1]
                for c in cnts:
                    area = cv2.contourArea(c)
                    frac = area / strip_area
                    if 0.01 <= frac <= 0.5:
                        x,y,bw,bh = cv2.boundingRect(c)
                        margin = 3
                        sh_, sw_ = strip.shape[:2]
                        if x<margin or y<margin or x+bw>sw_-margin or y+bh>sh_-margin:
                            continue
                        out_props.append([sx1+x, sy1+y, sx1+x+bw, sy1+y+bh])

        if out_props:
            out_props = np.array(out_props, dtype=np.float32)
            keep2 = non_max_suppression(out_props, np.ones(len(out_props)), 0.5)
            proposals_outside = out_props[keep2]

    all_proposals = np.concatenate([proposals_inside, proposals_outside], axis=0) \
                     if len(proposals_outside) > 0 else proposals_inside

    if len(all_proposals) == 0:
        return np.zeros((0,4), dtype=np.float32), paper_box
    return all_proposals, paper_box


def detect_and_measure_v2(net, image, scale_cm_per_px=None, conf_threshold=0.3,
                          paper_w_cm=None, paper_h_cm=None):
    """
    Improved hybrid pipeline using two-stage region proposal
    (paper region -> object within it).

    If paper_w_cm/paper_h_cm are given (e.g. 21.0, 29.7 for A4), scale
    is computed AUTOMATICALLY from the detected paper region's pixel
    size -- this is far more accurate than a manually guessed
    scale_cm_per_px, and removes a common source of ~2x errors.
    """
    proposals, paper_box = propose_regions_two_stage(image)
    print(f"  Paper/reference region found: "
          f"{'yes' if paper_box is not None else 'no'}")

    # ---- auto-calibrate scale from paper region if requested ----
    if paper_w_cm and paper_h_cm and paper_box is not None:
        ppx1,ppy1,ppx2,ppy2 = paper_box
        paper_w_px = ppx2 - ppx1
        paper_h_px = ppy2 - ppy1
        scale_x = paper_w_cm / paper_w_px
        scale_y = paper_h_cm / paper_h_px
        scale_cm_per_px = (scale_x + scale_y) / 2.0
        print(f"  Auto-calibrated scale from paper: "
              f"{paper_w_px:.0f}px={paper_w_cm}cm (x), "
              f"{paper_h_px:.0f}px={paper_h_cm}cm (y) "
              f"-> scale={scale_cm_per_px:.6f} cm/px")
        print(f"  (scale_x={scale_x:.6f}, scale_y={scale_y:.6f} -- "
              f"large difference between these indicates camera tilt)")
    elif scale_cm_per_px is None:
        print("  [!] No scale given. Provide --scale, or --paper_w_cm "
              "+ --paper_h_cm for auto-calibration.")
        scale_cm_per_px = 0.05  # fallback, will likely be wrong

    print(f"  Object candidates found inside it: {len(proposals)}")

    vis = image.copy()
    if paper_box is not None:
        px1,py1,px2,py2 = paper_box.astype(int)
        cv2.rectangle(vis, (px1,py1), (px2,py2), (255,140,0), 1)
        put_text(vis, "reference region", (px1, max(15,py1-6)),
                 (255,140,0), 0.4)

    if len(proposals) == 0:
        return vis, pd.DataFrame(
            columns=["x1","y1","x2","y2","width_px","height_px",
                     "width_cm","height_cm","area_cm2","confidence"])

    X = np.stack([extract_features(image, box) for box in proposals])
    cls_prob, box_pred, _ = net.forward(X)
    cls_prob = cls_prob.flatten()
    print(f"  Candidate confidences: "
          f"{[f'{s:.2f}' for s in sorted(cls_prob, reverse=True)]}")

    # Since candidates already come from careful classical segmentation
    # (not a blind dense grid), trust segmentation over the weak
    # classifier confidence -- take the largest valid candidate as the
    # object, but still report the network's confidence for reference.
    areas = (proposals[:,2]-proposals[:,0]) * (proposals[:,3]-proposals[:,1])
    order = np.argsort(-areas)

    rows = []
    for idx in order:
        box = proposals[idx]
        score = cls_prob[idx]
        x1,y1,x2,y2 = box
        w_px, h_px = x2-x1, y2-y1
        w_cm, h_cm = w_px*scale_cm_per_px, h_px*scale_cm_per_px

        cv2.rectangle(vis, (int(x1),int(y1)), (int(x2),int(y2)), (0,200,80), 2)
        put_text(vis, f"net_conf={score:.2f} | {w_cm:.1f}x{h_cm:.1f}cm",
                 (int(x1), int(max(15,y1-8))), (0,200,80), 0.5)

        rows.append({
            "x1":x1,"y1":y1,"x2":x2,"y2":y2,
            "width_px":w_px, "height_px":h_px,
            "width_cm":w_cm, "height_cm":h_cm,
            "area_cm2":w_cm*h_cm, "confidence":score
        })

    return vis, pd.DataFrame(rows)



    order = np.argsort(scores)[::-1]
    keep = []
    while len(order) > 0:
        i = order[0]
        keep.append(i)
        if len(order) == 1:
            break
        rest = order[1:]
        ious = box_iou(boxes[i:i+1], boxes[rest]).flatten()
        order = rest[ious < iou_threshold]
    return keep


# ============================================================================
# SECTION 7 — INFERENCE PIPELINE
# ============================================================================

def put_text(img, text, pos, color=(255,255,255), scale=0.55, thickness=1):
    cv2.putText(img, text, pos, cv2.FONT_HERSHEY_SIMPLEX,
                scale, (0,0,0), thickness+2, cv2.LINE_AA)
    cv2.putText(img, text, pos, cv2.FONT_HERSHEY_SIMPLEX,
                scale, color, thickness, cv2.LINE_AA)


def detect_and_measure(net, anchors, image, scale_cm_per_px,
                        conf_threshold=0.6, nms_iou=0.4,
                        train_img_size=128):
    """
    Run trained network over a real image using a sliding-anchor grid
    resized to match training scale, then decode + NMS + convert to cm.
    """
    h, w = image.shape[:2]
    resized = cv2.resize(image, (train_img_size, train_img_size))

    # Feature + forward pass for every anchor
    X = np.stack([extract_features(resized, a) for a in anchors])
    cls_prob, box_pred, _ = net.forward(X)
    cls_prob = cls_prob.flatten()

    keep_mask = cls_prob >= conf_threshold
    print(f"  Anchors above confidence {conf_threshold}: {keep_mask.sum()} / {len(anchors)}")

    if keep_mask.sum() == 0:
        return image.copy(), pd.DataFrame(
            columns=["x1","y1","x2","y2","width_px","height_px",
                     "width_cm","height_cm","area_cm2","confidence"])

    kept_anchors = anchors[keep_mask]
    kept_offsets = box_pred[keep_mask]
    kept_scores  = cls_prob[keep_mask]

    decoded_boxes = np.stack([
        decode_box(a, o) for a, o in zip(kept_anchors, kept_offsets)
    ])
    # Clip to training-image bounds
    decoded_boxes[:,[0,2]] = np.clip(decoded_boxes[:,[0,2]], 0, train_img_size)
    decoded_boxes[:,[1,3]] = np.clip(decoded_boxes[:,[1,3]], 0, train_img_size)

    keep_idx = non_max_suppression(decoded_boxes, kept_scores, nms_iou)
    final_boxes  = decoded_boxes[keep_idx]
    final_scores = kept_scores[keep_idx]

    # Scale boxes back to original image resolution
    sx, sy = w/train_img_size, h/train_img_size
    final_boxes[:,[0,2]] *= sx
    final_boxes[:,[1,3]] *= sy

    vis = image.copy()
    rows = []
    for box, score in zip(final_boxes, final_scores):
        x1,y1,x2,y2 = box
        w_px, h_px = x2-x1, y2-y1
        w_cm, h_cm = w_px*scale_cm_per_px, h_px*scale_cm_per_px
        area_cm2 = w_cm*h_cm

        cv2.rectangle(vis, (int(x1),int(y1)), (int(x2),int(y2)), (0,200,80), 2)
        put_text(vis, f"{score:.2f} | {w_cm:.1f}x{h_cm:.1f}cm",
                 (int(x1), int(max(15,y1-8))), (0,200,80), 0.5)

        rows.append({
            "x1":x1,"y1":y1,"x2":x2,"y2":y2,
            "width_px":w_px, "height_px":h_px,
            "width_cm":w_cm, "height_cm":h_cm,
            "area_cm2":area_cm2, "confidence":score
        })

    df = pd.DataFrame(rows)
    return vis, df


# ============================================================================
# MAIN
# ============================================================================

def interactive_reference(image):
    pts = []
    def cb(event,x,y,flags,param):
        if event == cv2.EVENT_LBUTTONDOWN and len(pts) < 2:
            pts.append((x,y))
            print(f"  Point {len(pts)}: ({x},{y})")
    win = "Click reference length - press Q when done"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)
    cv2.imshow(win, image); cv2.waitKey(1)
    cv2.setMouseCallback(win, cb)
    while True:
        disp = image.copy()
        for p in pts: cv2.circle(disp,p,6,(0,80,220),-1)
        if len(pts)==2: cv2.line(disp,pts[0],pts[1],(0,200,80),2)
        cv2.imshow(win, disp)
        if cv2.waitKey(1)&0xFF==ord('q') or len(pts)==2: break
    cv2.destroyAllWindows()
    return math.dist(pts[0],pts[1]) if len(pts)==2 else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--demo", action="store_true")
    ap.add_argument("--train", action="store_true")
    ap.add_argument("--image", default=None)
    ap.add_argument("--scale", type=float, default=None)
    ap.add_argument("--interactive_ref", action="store_true")
    ap.add_argument("--ref_cm", type=float, default=None)
    ap.add_argument("--epochs", type=int, default=60)
    ap.add_argument("--n_samples", type=int, default=400)
    ap.add_argument("--conf", type=float, default=0.6)
    ap.add_argument("--save_weights", default="weights_scratch.npz")
    ap.add_argument("--load_weights", default=None)
    ap.add_argument("--hard_neg_image", default=None,
                    help="Photo of background surface ONLY (no object) "
                         "used to mine and correct false positives")
    ap.add_argument("--hybrid", action="store_true",
                    help="Use classical contour proposals instead of "
                         "dense anchor grid -- recommended for single/"
                         "few-object scenes, far fewer false positives")
    ap.add_argument("--v2", action="store_true",
                    help="RECOMMENDED: two-stage pipeline (find paper/"
                         "reference region, then find object inside it). "
                         "Fixes false positives on paper/background.")
    ap.add_argument("--paper_w_cm", type=float, default=None,
                    help="Real width of reference sheet in cm (e.g. 21.0 "
                         "for A4 portrait width). Auto-calibrates scale "
                         "from the detected paper region -- more accurate "
                         "than guessing --scale.")
    ap.add_argument("--paper_h_cm", type=float, default=None,
                    help="Real height of reference sheet in cm (e.g. 29.7 "
                         "for A4 portrait height)")
    args = ap.parse_args()

    print("\n" + "="*58)
    print("  D1 FROM SCRATCH - numpy/opencv/pandas only, no pretrained model")
    print("="*58)

    os.makedirs("results", exist_ok=True)

    if args.demo:
        net, anchors = train_network(n_samples=args.n_samples,
                                     epochs=args.epochs)
        net.save(args.save_weights)

        test_img, test_gt = generate_synthetic_sample(128)
        test_img_big = cv2.resize(test_img, (512,512))
        vis, df = detect_and_measure(net, anchors, test_img_big,
                                     scale_cm_per_px=0.05,
                                     conf_threshold=args.conf)
        cv2.imwrite("results/scratch_demo_result.jpg", vis)
        print(f"\n  Saved -> results/scratch_demo_result.jpg")
        print("\n  Detections:")
        print(df.to_string(index=False))
        df.to_csv("results/scratch_demo_detections.csv", index=False)
        return

    if args.load_weights and os.path.exists(args.load_weights):
        net = TinyDetectorNet()
        net.load(args.load_weights)
        anchors = generate_anchors(128, stride=16, scales=(32,56),
                                   ratios=(0.5,1.0,2.0))
    else:
        net, anchors = train_network(n_samples=args.n_samples,
                                     epochs=args.epochs)
        net.save(args.save_weights)

    if not args.image:
        print("\n  No --image given. Use --demo to test end-to-end,")
        print("  or --image <path> with --scale / --interactive_ref.")
        return

    if args.hard_neg_image and os.path.exists(args.hard_neg_image):
        print(f"\n  Mining hard negatives from: {args.hard_neg_image}")
        bg_img = cv2.imread(args.hard_neg_image)
        hard_neg_feats = mine_hard_negatives(net, anchors, bg_img)
        net = train_with_hard_negatives(net, anchors, hard_neg_feats,
                                        epochs=20, lr=0.02)
        net.save(args.save_weights)

    img = cv2.imread(args.image)
    if img is None:
        raise FileNotFoundError(args.image)

    if args.scale:
        scale = args.scale
    elif args.paper_w_cm and args.paper_h_cm and args.v2:
        scale = None  # will be auto-calibrated inside detect_and_measure_v2
    elif args.interactive_ref and args.ref_cm:
        ref_px = interactive_reference(img)
        if not ref_px:
            print("  [!] No reference selected."); return
        scale = args.ref_cm / ref_px
        print(f"  Reference: {ref_px:.2f}px = {args.ref_cm}cm -> "
              f"scale={scale:.6f}cm/px")
    else:
        print("  [!] Provide --scale or --interactive_ref with --ref_cm")
        return

    if args.v2:
        vis, df = detect_and_measure_v2(net, img, scale,
                                        conf_threshold=args.conf,
                                        paper_w_cm=args.paper_w_cm,
                                        paper_h_cm=args.paper_h_cm)
    elif args.hybrid:
        vis, df = detect_and_measure_hybrid(net, img, scale,
                                            conf_threshold=args.conf)
    else:
        vis, df = detect_and_measure(net, anchors, img, scale,
                                     conf_threshold=args.conf)
    cv2.imwrite("results/scratch_result.jpg", vis)
    print(f"\n  Saved -> results/scratch_result.jpg")
    print("\n  Detections:")
    print(df.to_string(index=False) if len(df) else "  (none above threshold)")
    df.to_csv("results/scratch_detections.csv", index=False)
    print(f"  Saved -> results/scratch_detections.csv")


if __name__ == "__main__":
    main()