"""
METHOD B4: Perspective-n-Point (PnP)
=======================================
WHAT IT DOES:
    Given n 3D world points and their corresponding 2D image projections,
    PnP recovers the camera POSE (rotation R + translation t) relative to
    the object. Once pose is known:
        - Distance from camera to object = ||t|| (magnitude of translation)
        - Object dimensions from 3D point differences
        - Any real-world measurement directly from 3D coordinates

MATHEMATICAL FOUNDATION:
    The pinhole projection equation:
        s × [u,v,1]ᵀ = K × [R|t] × [X,Y,Z,1]ᵀ

    Where:
        K       = camera intrinsic matrix (3×3)
        R       = rotation matrix (3×3) — how object is oriented
        t       = translation vector (3×1) — where object is in space
        [X,Y,Z] = 3D world point (known)
        [u,v]   = 2D image point (detected)
        s       = scale factor (depth)

    PnP solves for [R|t] given K, world points, and image points.

SOLVING METHODS (all implemented here):
    SOLVEPNP_ITERATIVE  — Levenberg-Marquardt, most accurate, needs good init
    SOLVEPNP_EPNP       — Efficient PnP, fast, works with n>=4 points
    SOLVEPNP_P3P        — Minimal solver, exactly 3 points, multiple solutions
    SOLVEPNP_IPPE       — Planar objects only, very fast
    SOLVEPNP_IPPE_SQUARE— Square planar targets (ArUco markers)
    RANSAC              — Robust to outlier point correspondences

LOSS FUNCTION:
    Reprojection error (same as calibration):
        L = Σ ||p_image - π(K, R, t, P_world)||²

    Where π() is the projection function.
    After solving, reprojects world points back and measures pixel error.
    Good solution: error < 2.0 pixels for measurement use.

WHAT IMAGE TO USE:

    OPTION A — Checkerboard / known pattern (most accurate):
        Same checkerboard used in B1/B2 calibration.
        Photograph from any angle.
        Known 3D corner positions → detected 2D corners → solve PnP.

    OPTION B — ArUco marker (easiest setup):
        Print an ArUco marker (generated by --generate_marker).
        Place it on or beside your object.
        Code detects corners automatically — no manual clicking.

    OPTION C — Manual 3D-2D correspondences:
        Any image where you know at least 4 points' real 3D positions.
        Example: corners of a known-size box, corners of an A4 sheet,
                 four sticker markers at measured positions.

    OPTION D — Demo mode:
        Run --demo for fully synthetic test, no images needed.

WHAT YOU NEED BEFORE RUNNING:
    Camera calibration data (calib_data.npz from B1).
    If you don't have it: run --demo (uses synthetic K) or
    run B1 first: python method_b1_pinhole.py --calibrate

FOLDER STRUCTURE:
    images/
      method_b4_pnp/
        object.jpg    ← image of object with known reference points

HOW TO RUN:

    # Full demo (no images, no calibration file needed):
    python method_b4_pnp.py --demo

    # Generate a printable ArUco marker:
    python method_b4_pnp.py --generate_marker

    # Run with ArUco marker in image (auto-detects corners):
    python method_b4_pnp.py --aruco \
        --image images/method_b4_pnp/aruco_scene.jpg \
        --marker_cm 10.0 \
        --calib calib_data.npz

    # Run with checkerboard image:
    python method_b4_pnp.py --checkerboard \
        --image images/method_b4_pnp/checker.jpg \
        --board_w 9 --board_h 6 --sq_cm 2.5 \
        --calib calib_data.npz

    # Run with manually specified point correspondences:
    python method_b4_pnp.py --manual \
        --world_pts  0 0 0   10 0 0   10 8 0   0 8 0 \
        --image_pts  120 340  450 335  448 210  122 215 \
        --calib calib_data.npz \
        --image images/method_b4_pnp/object.jpg

    # Compare all PnP solvers on same data:
    python method_b4_pnp.py --demo --compare_solvers

PARAMETERS:
    --calib           : path to calibration .npz from B1 (default: calib_data.npz)
    --image           : input image path
    --mode            : iterative | epnp | p3p | ippe (default: epnp)
    --compare_solvers : run all solver methods and compare results
    --marker_cm       : ArUco marker real size in cm
    --board_w/h       : checkerboard inner corners
    --sq_cm           : checkerboard square size in cm
    --world_pts       : manual 3D points as flat list: X1 Y1 Z1 X2 Y2 Z2 ...
    --image_pts       : corresponding 2D points: u1 v1 u2 v2 ...
    --measure_pts     : two 3D world points to measure distance between
    --demo            : synthetic test, no files needed
    --generate_marker : save a printable ArUco marker image
"""

import cv2
import numpy as np
import argparse
import os
import sys
import math

# ── helpers ────────────────────────────────────────────────────────────────────

def put_text(img, text, pos, color=(255,255,255), scale=0.55, thickness=1):
    cv2.putText(img, text, pos, cv2.FONT_HERSHEY_SIMPLEX,
                scale, (0,0,0), thickness+2, cv2.LINE_AA)
    cv2.putText(img, text, pos, cv2.FONT_HERSHEY_SIMPLEX,
                scale, color, thickness, cv2.LINE_AA)

def save_result(img, suffix, out_dir="results"):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"method_b4_{suffix}.jpg")
    cv2.imwrite(path, img)
    print(f"  Saved → {path}")
    return path

def show_metrics(title, metrics):
    print(f"\n{'═'*54}")
    print(f"  {title}")
    print(f"{'═'*54}")
    for k, v in metrics.items():
        if k.startswith("─"):
            print(f"  {'─'*50}")
        else:
            print(f"  {k:<36} {v}")
    print(f"{'═'*54}\n")

def rotation_matrix_to_euler(R):
    """Convert 3×3 rotation matrix to Euler angles (degrees)."""
    sy = math.sqrt(R[0,0]**2 + R[1,0]**2)
    singular = sy < 1e-6
    if not singular:
        x = math.atan2( R[2,1], R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2( R[1,0], R[0,0])
    else:
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
    return np.degrees([x, y, z])

def compute_reprojection_error(world_pts, img_pts, rvec, tvec, K, D):
    """Compute mean reprojection error in pixels."""
    projected, _ = cv2.projectPoints(
        world_pts.astype(np.float32),
        rvec, tvec, K, D)
    projected = projected.reshape(-1, 2)
    img_pts_   = img_pts.reshape(-1, 2)
    errors = np.linalg.norm(projected - img_pts_, axis=1)
    return float(np.mean(errors)), float(np.max(errors)), projected

def draw_axes(img, K, D, rvec, tvec, length_cm=5.0):
    """
    Draw 3D coordinate axes on image at object origin.
    Red=X, Green=Y, Blue=Z
    """
    axis_pts = np.float32([
        [0,       0,       0      ],   # origin
        [length_cm, 0,     0      ],   # X
        [0,       length_cm, 0    ],   # Y
        [0,       0,       -length_cm] # Z (into scene)
    ])
    img_pts, _ = cv2.projectPoints(axis_pts, rvec, tvec, K, D)
    img_pts = img_pts.astype(int).reshape(-1, 2)

    origin = tuple(img_pts[0])
    cv2.arrowedLine(img, origin, tuple(img_pts[1]), (0,0,220),   2, tipLength=0.2)
    cv2.arrowedLine(img, origin, tuple(img_pts[2]), (0,200,0),   2, tipLength=0.2)
    cv2.arrowedLine(img, origin, tuple(img_pts[3]), (220,80,0),  2, tipLength=0.2)
    put_text(img, "X", (img_pts[1][0]+5, img_pts[1][1]), (0,0,220),   0.45)
    put_text(img, "Y", (img_pts[2][0]+5, img_pts[2][1]), (0,200,0),   0.45)
    put_text(img, "Z", (img_pts[3][0]+5, img_pts[3][1]), (220,80,0),  0.45)
    return img

def draw_cube(img, K, D, rvec, tvec, size_cm=5.0):
    """Draw a 3D cube overlay at the object origin."""
    s = size_cm
    cube_pts = np.float32([
        [0,0,0],[s,0,0],[s,s,0],[0,s,0],   # bottom face
        [0,0,-s],[s,0,-s],[s,s,-s],[0,s,-s] # top face
    ])
    img_pts, _ = cv2.projectPoints(cube_pts, rvec, tvec, K, D)
    img_pts = img_pts.astype(int).reshape(-1, 2)

    # Bottom face edges
    for i,j in [(0,1),(1,2),(2,3),(3,0)]:
        cv2.line(img, tuple(img_pts[i]), tuple(img_pts[j]), (0,200,80), 1)
    # Top face edges
    for i,j in [(4,5),(5,6),(6,7),(7,4)]:
        cv2.line(img, tuple(img_pts[i]), tuple(img_pts[j]), (0,140,220), 1)
    # Vertical edges
    for i in range(4):
        cv2.line(img, tuple(img_pts[i]), tuple(img_pts[i+4]), (200,200,0), 1)
    return img

# ── calibration loader ─────────────────────────────────────────────────────────

def load_or_default_calibration(calib_path, img_shape=None):
    """Load calibration from file, or build a reasonable default."""
    if calib_path and os.path.exists(calib_path):
        data = np.load(calib_path)
        K = data["camera_matrix"]
        D = data["dist_coeffs"]
        print(f"  Calibration loaded: {calib_path}")
        return K, D
    else:
        if calib_path:
            print(f"  [!] Calibration not found: {calib_path}")
        print("  Using approximate default camera matrix.")
        h = img_shape[0] if img_shape else 600
        w = img_shape[1] if img_shape else 800
        f  = max(w, h) * 1.2
        K  = np.array([[f,0,w/2],[0,f,h/2],[0,0,1]], dtype=np.float64)
        D  = np.zeros((1,5), dtype=np.float64)
        return K, D

# ── ArUco marker generation ────────────────────────────────────────────────────

def generate_aruco_marker(marker_id=0, size_px=400,
                           out_path="print_this_aruco.png"):
    """Generate a printable ArUco marker."""
    try:
        aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
        marker_img = np.zeros((size_px, size_px), dtype=np.uint8)
        cv2.aruco.generateImageMarker(aruco_dict, marker_id, size_px, marker_img)
        # Add white border
        canvas = np.ones((size_px+80, size_px+80), dtype=np.uint8)*255
        canvas[40:40+size_px, 40:40+size_px] = marker_img
        cv2.imwrite(out_path, canvas)
        print(f"\n  ArUco marker saved → {out_path}")
        print(f"  Marker ID: {marker_id} | Dictionary: DICT_4X4_50")
        print(f"  Print at known size. Measure printed marker width → use as --marker_cm")
        return canvas
    except AttributeError:
        print("  [!] ArUco not available in this OpenCV build.")
        print("      Install: pip install opencv-contrib-python")
        return None

# ── synthetic demo ─────────────────────────────────────────────────────────────

def make_demo_scene(out_path="images/method_b4_pnp/demo_scene.jpg",
                    board_w=7, board_h=5, sq_px=60):
    """
    Create synthetic scene: checkerboard at a known pose.
    Returns image + ground-truth 3D/2D correspondences.
    """
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    IMG_W, IMG_H = 800, 600
    canvas = np.ones((IMG_H, IMG_W, 3), dtype=np.uint8) * 200

    # Background gradient
    for y in range(IMG_H):
        v = int(190 + 25*(y/IMG_H))
        canvas[y,:] = (v, v+5, v+10)

    # Draw checkerboard at slight perspective
    cols, rows = board_w+1, board_h+1
    margin_x, margin_y = 120, 100
    sq = sq_px

    # Apply slight perspective skew
    for r in range(rows):
        for c in range(cols):
            if (r+c) % 2 == 0:
                # Trapezoid perspective: compress top
                persp = 0.85 + 0.15*(r/rows)
                x1 = int(margin_x + c*sq*persp + r*3)
                y1 = int(margin_y + r*sq*0.88)
                x2 = int(x1 + sq*persp)
                y2 = int(y1 + sq*0.88)
                cv2.rectangle(canvas, (x1,y1),(x2,y2),(30,30,30),-1)

    # Draw a target object (rice grain shape)
    cv2.ellipse(canvas,(580,420),(80,30),10,0,360,(120,160,80),-1)
    cv2.ellipse(canvas,(580,420),(80,30),10,0,360,(60,100,40),2)
    put_text(canvas,"Target object",(510,395),(60,100,40),0.4)

    # Add subtle noise
    noise = np.random.randint(-6,6,canvas.shape,dtype=np.int16)
    canvas = np.clip(canvas.astype(np.int16)+noise,0,255).astype(np.uint8)

    cv2.imwrite(out_path, canvas)

    # Build synthetic 3D-2D correspondences for 4 corners of the board
    # Ground truth object corners in world coords (cm)
    sq_cm = 2.5
    world_pts = np.float32([
        [0,                   0,                   0],
        [board_w * sq_cm,     0,                   0],
        [board_w * sq_cm,     board_h * sq_cm,     0],
        [0,                   board_h * sq_cm,     0],
        [board_w/2 * sq_cm,   board_h/2 * sq_cm,   0],  # centre
    ])

    # Corresponding approximate image pixels (from our drawn board)
    img_pts = np.float32([
        [120,  100],
        [120 + (board_w)*sq_px*0.85+board_h*3,   100],
        [120 + board_w*sq_px*1.0 +board_h*3,     100+board_h*sq_px*0.88],
        [120,                                      100+board_h*sq_px*0.88],
        [120 + board_w*sq_px*0.5,                 100+board_h*sq_px*0.44],
    ])

    return canvas, world_pts, img_pts, sq_cm

# ── core PnP solver ────────────────────────────────────────────────────────────

def pixel_to_world_on_plane(pixel_pt, K, D, rvec, tvec):
    """
    Given a pixel point known to lie on the Z=0 world plane
    (same plane as your reference points), back-project it to
    find its real-world (X, Y, 0) coordinate.

    This lets you measure ANY point in the image once pose is
    solved from 4+ known reference points on that plane.
    """
    R, _ = cv2.Rodrigues(rvec)

    # Undistort the pixel point first
    pt = np.array([[pixel_pt]], dtype=np.float32)
    undist_pt = cv2.undistortPoints(pt, K, D, P=K)
    u, v = undist_pt[0,0]

    # Ray direction in camera coords
    K_inv = np.linalg.inv(K)
    ray_cam = K_inv @ np.array([u, v, 1.0])

    # Rotate ray into world coords
    ray_world = R.T @ ray_cam
    cam_pos_world = -R.T @ tvec.flatten()

    # Intersect with Z=0 plane:
    # cam_pos_world[2] + s * ray_world[2] = 0
    if abs(ray_world[2]) < 1e-8:
        return None
    s = -cam_pos_world[2] / ray_world[2]
    world_pt = cam_pos_world + s * ray_world
    return world_pt  # [X, Y, 0] in cm

def measure_object_points(image, K, D, rvec, tvec, pixel_points, labels=None):
    """
    Measure real-world distances between arbitrary clicked pixel
    points, using the pose already solved from reference points.

    Args:
        pixel_points : list of (x,y) pixel coords on the same
                       plane as your reference points (e.g. A4 sheet)
        labels        : optional names for each point
    """
    if labels is None:
        labels = [f"O{i+1}" for i in range(len(pixel_points))]

    world_coords = []
    for pt in pixel_points:
        w = pixel_to_world_on_plane(pt, K, D, rvec, tvec)
        world_coords.append(w)

    vis = image.copy()
    metrics = {"─ Object Points (world coords) ─": ""}

    for i, (px, w) in enumerate(zip(pixel_points, world_coords)):
        cv2.circle(vis, tuple(map(int,px)), 7, (0,140,255), 2)
        put_text(vis, labels[i], (int(px[0])+9, int(px[1])-9),
                 (0,140,255), 0.45)
        if w is not None:
            metrics[f"  {labels[i]} pixel"] = f"{px}"
            metrics[f"  {labels[i]} world (X,Y,cm)"] = f"({w[0]:.3f}, {w[1]:.3f})"

    metrics["─ Object Distances ─"] = ""
    n = len(pixel_points)
    for i in range(n):
        for j in range(i+1, n):
            if world_coords[i] is not None and world_coords[j] is not None:
                d = np.linalg.norm(world_coords[i] - world_coords[j])
                cv2.line(vis, tuple(map(int,pixel_points[i])),
                         tuple(map(int,pixel_points[j])), (0,220,120), 2)
                mx = int((pixel_points[i][0]+pixel_points[j][0])/2)
                my = int((pixel_points[i][1]+pixel_points[j][1])/2) - 10
                put_text(vis, f"{d:.3f}cm", (mx,my), (0,220,120), 0.5)
                metrics[f"  {labels[i]}→{labels[j]}"] = f"► {d:.4f} cm"

    save_result(vis, "object_measurement")
    show_metrics("B4 — Object Measurement (via solved pose)", metrics)
    return world_coords, metrics

_obj_pts_clicked = []

def _mouse_obj(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        _obj_pts_clicked.append((x, y))
        print(f"  Object point {len(_obj_pts_clicked)}: ({x},{y})")

def interactive_object_points(image_path):
    img = cv2.imread(image_path)
    if img is None:
        return []
    _obj_pts_clicked.clear()
    print("\n  Click points on your OBJECT to measure. Press Q when done.\n")
    win = "Click object points - press Q when done"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)
    cv2.imshow(win, img)
    cv2.waitKey(1)
    cv2.setMouseCallback(win, _mouse_obj)
    while True:
        disp = img.copy()
        for i, pt in enumerate(_obj_pts_clicked):
            cv2.circle(disp, pt, 6, (0,140,255), -1)
            put_text(disp, f"O{i+1}", (pt[0]+8,pt[1]-8), (0,140,255), 0.4)
        cv2.imshow(win, disp)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cv2.destroyAllWindows()
    return _obj_pts_clicked.copy()


SOLVER_MAP = {
    "iterative": cv2.SOLVEPNP_ITERATIVE,
    "epnp":      cv2.SOLVEPNP_EPNP,
    "ippe":      cv2.SOLVEPNP_IPPE,
}

def solve_pnp(world_pts, img_pts, K, D, method="epnp"):
    """
    Solve PnP — find camera pose [R|t] given 3D-2D correspondences.

    Args:
        world_pts : (N,3) float32 — 3D points in object/world coordinates (cm)
        img_pts   : (N,2) float32 — corresponding 2D image pixel coordinates
        K         : (3,3) camera matrix
        D         : distortion coefficients
        method    : solver name string

    Returns:
        rvec      : rotation vector (3,1) — Rodrigues form
        tvec      : translation vector (3,1) — camera position in cm
        R         : rotation matrix (3,3)
        success   : bool
    """
    solver = SOLVER_MAP.get(method, cv2.SOLVEPNP_EPNP)

    n = len(world_pts)
    if method == "p3p" and n != 4:
        print(f"  [!] P3P requires exactly 4 points, got {n}. Switching to EPNP.")
        solver = cv2.SOLVEPNP_EPNP

    success, rvec, tvec = cv2.solvePnP(
        world_pts.astype(np.float32),
        img_pts.astype(np.float32),
        K, D,
        flags=solver)

    if not success:
        return None, None, None, False

    # Convert Rodrigues rotation vector → rotation matrix
    R, _ = cv2.Rodrigues(rvec)
    return rvec, tvec, R, True

def solve_pnp_ransac(world_pts, img_pts, K, D,
                      reprojection_thresh=8.0, iterations=200):
    """
    RANSAC PnP — robust to outlier correspondences.
    Returns inlier mask in addition to pose.
    """
    success, rvec, tvec, inliers = cv2.solvePnPRansac(
        world_pts.astype(np.float32),
        img_pts.astype(np.float32),
        K, D,
        iterationsCount=iterations,
        reprojectionError=reprojection_thresh,
        confidence=0.99)

    if not success or inliers is None:
        return None, None, None, False, np.array([])

    R, _ = cv2.Rodrigues(rvec)
    inlier_mask = inliers.flatten()
    n_inliers = len(inlier_mask)
    n_total   = len(world_pts)
    print(f"  RANSAC: {n_inliers}/{n_total} inliers "
          f"({100*n_inliers/n_total:.1f}%)")
    return rvec, tvec, R, True, inlier_mask

# ── measurement from pose ──────────────────────────────────────────────────────

def measure_from_pose(rvec, tvec, R, world_pts):
    """
    Extract all useful measurements from solved pose.

    Camera centre in world coords = -R^T × t
    Distance to origin = ||t||
    """
    # Camera position in world frame
    cam_pos_world = -R.T @ tvec.flatten()

    # Distance from camera to world origin
    dist_to_origin = np.linalg.norm(tvec)

    # Distances between world points (ground truth 3D distances)
    pt_distances = {}
    n = len(world_pts)
    for i in range(n):
        for j in range(i+1, n):
            d = np.linalg.norm(world_pts[i] - world_pts[j])
            pt_distances[f"P{i+1}→P{j+1}"] = d

    # Euler angles from rotation matrix
    euler = rotation_matrix_to_euler(R)

    # Object-to-camera vector direction
    z_axis_world = R.T @ np.array([0,0,1])

    return {
        "dist_to_origin_cm":  dist_to_origin,
        "cam_pos_world":      cam_pos_world,
        "euler_deg":          euler,
        "pt_distances_cm":    pt_distances,
        "z_axis_world":       z_axis_world,
    }

# ── full pipeline ──────────────────────────────────────────────────────────────

def run_pnp(image, world_pts, img_pts, K, D,
            method="epnp", use_ransac=False,
            draw_axis=True, draw_box=True,
            axis_len_cm=5.0, label="B4 PnP"):
    """
    Full PnP pipeline: solve → measure → visualise → report.
    """
    vis = image.copy()
    h, w = vis.shape[:2]

    print(f"\n  Solver: {method.upper()}"
          f"{'  + RANSAC' if use_ransac else ''}")
    print(f"  Points: {len(world_pts)} correspondences")

    # ── solve ──────────────────────────────────────────────────────
    inlier_mask = None
    if use_ransac:
        rvec, tvec, R, ok, inlier_mask = solve_pnp_ransac(
            world_pts, img_pts, K, D)
    else:
        rvec, tvec, R, ok = solve_pnp(world_pts, img_pts, K, D, method)

    if not ok:
        print("  [!] PnP failed. Check point correspondences.")
        return None, None

    # ── reprojection error ─────────────────────────────────────────
    mean_err, max_err, proj_pts = compute_reprojection_error(
        world_pts, img_pts, rvec, tvec, K, D)

    quality = ("EXCELLENT" if mean_err < 1.0 else
               "GOOD"      if mean_err < 3.0 else
               "ACCEPTABLE" if mean_err < 8.0 else
               "POOR")

    # ── measurements ───────────────────────────────────────────────
    meas = measure_from_pose(rvec, tvec, R, world_pts)

    # ── visualise detected vs projected points ─────────────────────
    for i, (pt_det, pt_proj) in enumerate(zip(
            img_pts.reshape(-1,2), proj_pts)):

        # Detected point (filled circle)
        is_inlier = (inlier_mask is None or i in inlier_mask)
        col_det  = (0,200,80)  if is_inlier else (0,0,200)
        col_proj = (0,80,220)  if is_inlier else (100,100,100)

        cv2.circle(vis, tuple(pt_det.astype(int)),  7, col_det,  2)
        cv2.circle(vis, tuple(pt_proj.astype(int)), 4, col_proj, -1)

        # Error line (detected → projected)
        cv2.line(vis, tuple(pt_det.astype(int)),
                 tuple(pt_proj.astype(int)), (200,200,0), 1)

        # Label
        put_text(vis, f"P{i+1}",
                 (int(pt_det[0])+9, int(pt_det[1])-9),
                 col_det, 0.42)

    # ── draw 3D axes ───────────────────────────────────────────────
    if draw_axis:
        draw_axes(vis, K, D, rvec, tvec, axis_len_cm)

    # ── draw 3D cube ───────────────────────────────────────────────
    if draw_box:
        draw_cube(vis, K, D, rvec, tvec, axis_len_cm)

    # ── legend ─────────────────────────────────────────────────────
    leg_x, leg_y = 10, h - 120
    cv2.rectangle(vis,(leg_x-5,leg_y-15),(leg_x+220,leg_y+75),
                  (15,15,20),-1)
    cv2.circle(vis,(leg_x+8,leg_y+2),6,(0,200,80),2)
    put_text(vis,"Detected point",(leg_x+18,leg_y+6),(0,200,80),0.38)
    cv2.circle(vis,(leg_x+8,leg_y+20),4,(0,80,220),-1)
    put_text(vis,"Reprojected point",(leg_x+18,leg_y+24),(0,80,220),0.38)
    cv2.line(vis,(leg_x+2,leg_y+38),(leg_x+14,leg_y+38),(200,200,0),1)
    put_text(vis,"Reprojection error",(leg_x+18,leg_y+42),(200,200,0),0.38)
    for i,(lbl,col) in enumerate([("X axis",(0,0,220)),
                                    ("Y axis",(0,200,0)),
                                    ("Z axis",(220,80,0))]):
        put_text(vis,lbl,(leg_x+18+i*62,leg_y+60),col,0.35)

    # ── info panel at bottom ───────────────────────────────────────
    panel_h = 55
    panel = np.zeros((panel_h, w, 3), dtype=np.uint8)
    cv2.rectangle(panel,(0,0),(w,panel_h),(12,15,22),-1)

    euler = meas["euler_deg"]
    dist  = meas["dist_to_origin_cm"]
    tvec_f= tvec.flatten()
    put_text(panel,
             f"Dist: {dist:.2f}cm  |  "
             f"t=({tvec_f[0]:.1f},{tvec_f[1]:.1f},{tvec_f[2]:.1f})cm  |  "
             f"Euler: Rx={euler[0]:.1f}° Ry={euler[1]:.1f}° Rz={euler[2]:.1f}°",
             (8,18),(140,180,240),0.42)
    put_text(panel,
             f"Solver: {method.upper()}  |  "
             f"Reproj err: {mean_err:.3f}px (mean) {max_err:.3f}px (max)  |  "
             f"Quality: {quality}  |  Points: {len(world_pts)}",
             (8,40),(100,220,140),0.42)

    combined = np.vstack([vis, panel])
    save_result(combined, f"result_{method}")

    # ── metrics ────────────────────────────────────────────────────
    metrics = {
        "─ Solver ─":                     "",
        "  Method":                       method.upper() + (" + RANSAC" if use_ransac else ""),
        "  Point correspondences":        str(len(world_pts)),
        "─ Rotation (Rodrigues rvec) ─":  "",
        "  rx":                           f"{float(rvec.flatten()[0]):.6f} rad",
        "  ry":                           f"{float(rvec.flatten()[1]):.6f} rad",
        "  rz":                           f"{float(rvec.flatten()[2]):.6f} rad",
        "─ Euler Angles ─":               "",
        "  Roll  (Rx)":                   f"{euler[0]:.3f}°",
        "  Pitch (Ry)":                   f"{euler[1]:.3f}°",
        "  Yaw   (Rz)":                   f"{euler[2]:.3f}°",
        "─ Translation (tvec) ─":         "",
        "  tx":                           f"{tvec_f[0]:.4f} cm",
        "  ty":                           f"{tvec_f[1]:.4f} cm",
        "  tz (depth)":                   f"{tvec_f[2]:.4f} cm",
        "─ Distance ─":                   "",
        "  Camera to object origin":      f"► {dist:.4f} cm",
        "  Camera position (world)":      f"({meas['cam_pos_world'][0]:.2f}, "
                                          f"{meas['cam_pos_world'][1]:.2f}, "
                                          f"{meas['cam_pos_world'][2]:.2f}) cm",
        "─ 3D Point Distances ─":         "",
    }
    for pair, d in meas["pt_distances_cm"].items():
        metrics[f"  {pair}"] = f"{d:.4f} cm"

    metrics.update({
        "─ Reprojection Error ─":         "",
        "  Mean error":                   f"{mean_err:.4f} px",
        "  Max  error":                   f"{max_err:.4f} px",
        "  Quality":                      quality,
        "─ Formula ─":                    "",
        "  s×[u,v,1]ᵀ = K×[R|t]×[X,Y,Z,1]ᵀ": "",
        "  ||t|| = camera-to-origin dist":      f"{dist:.4f} cm",
    })

    show_metrics(f"B4 — PnP Results ({method.upper()})", metrics)
    return rvec, tvec

# ── solver comparison ──────────────────────────────────────────────────────────

def compare_all_solvers(image, world_pts, img_pts, K, D):
    """Run all available solvers and compare their reprojection errors."""
    print("\n" + "═"*54)
    print("  B4 — Solver Comparison")
    print("═"*54)

    solvers = ["iterative", "epnp", "ippe"]
    results = {}

    for method in solvers:
        try:
            rvec, tvec, R, ok = solve_pnp(world_pts, img_pts, K, D, method)
            if ok:
                mean_err, max_err, _ = compute_reprojection_error(
                    world_pts, img_pts, rvec, tvec, K, D)
                dist = float(np.linalg.norm(tvec))
                results[method] = {
                    "mean_err": mean_err,
                    "max_err":  max_err,
                    "dist":     dist,
                    "rvec":     rvec,
                    "tvec":     tvec,
                }
                print(f"  {method.upper():<12} "
                      f"reproj={mean_err:.3f}px  "
                      f"dist={dist:.2f}cm")
            else:
                print(f"  {method.upper():<12} FAILED")
        except Exception as e:
            print(f"  {method.upper():<12} ERROR: {e}")

    # RANSAC
    try:
        rvec_r, tvec_r, R_r, ok_r, _ = solve_pnp_ransac(world_pts, img_pts, K, D)
        if ok_r:
            me, mx, _ = compute_reprojection_error(
                world_pts, img_pts, rvec_r, tvec_r, K, D)
            dist_r = float(np.linalg.norm(tvec_r))
            results["ransac"] = {"mean_err":me,"max_err":mx,"dist":dist_r}
            print(f"  {'RANSAC':<12} reproj={me:.3f}px  dist={dist_r:.2f}cm")
    except Exception as e:
        print(f"  {'RANSAC':<12} ERROR: {e}")

    # Build comparison visualisation
    if results:
        vis_panels = []
        for method, res in results.items():
            if "rvec" in res:
                panel = image.copy()
                _, _, proj = compute_reprojection_error(
                    world_pts, img_pts,
                    res["rvec"], res["tvec"], K, D)
                for pt in proj:
                    cv2.circle(panel,tuple(pt.astype(int)),5,(0,80,220),-1)
                for pt in img_pts.reshape(-1,2):
                    cv2.circle(panel,tuple(pt.astype(int)),7,(0,200,80),2)
                draw_axes(panel,K,D,res["rvec"],res["tvec"],4.0)
                put_text(panel,
                         f"{method.upper()} | err={res['mean_err']:.2f}px",
                         (8,22),(255,220,80),0.5)
                vis_panels.append(panel)

        if len(vis_panels) >= 2:
            h,w = vis_panels[0].shape[:2]
            rows = []
            for i in range(0,len(vis_panels),2):
                pair = vis_panels[i:i+2]
                if len(pair)==2:
                    rows.append(np.hstack(pair))
                else:
                    blank = np.zeros_like(pair[0])
                    rows.append(np.hstack([pair[0],blank]))
            grid = np.vstack(rows)
            save_result(grid,"solver_comparison")

    print("═"*54)
    return results

# ── checkerboard-based PnP ────────────────────────────────────────────────────

def run_pnp_checkerboard(image_path, board_w, board_h, sq_cm, K, D,
                          method="epnp"):
    """Detect checkerboard corners and solve PnP."""
    img  = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    board_size = (board_w, board_h)

    # Build 3D world points
    objp = np.zeros((board_w*board_h,3), np.float32)
    objp[:,:2] = np.mgrid[0:board_w,0:board_h].T.reshape(-1,2)
    objp *= sq_cm

    criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,30,0.001)
    ret, corners = cv2.findChessboardCorners(gray, board_size, None)

    if not ret:
        print("  [!] Checkerboard not detected. Check image quality.")
        return None, None

    corners = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)

    print(f"  Checkerboard detected: {board_w}×{board_h} = "
          f"{board_w*board_h} corners")

    return run_pnp(img, objp, corners.reshape(-1,2), K, D,
                   method=method, label="Checkerboard PnP")

# ── ArUco-based PnP ──────────────────────────────────────────────────────────

def run_pnp_aruco(image_path, marker_cm, K, D, method="ippe",
                   object_pixel_pts=None, interactive_object=False):
    """Detect ArUco marker and solve PnP using its 4 corners.
    If object_pixel_pts given (or interactive_object=True), also
    measures those points on the same plane as the marker.
    """
    try:
        aruco_dict   = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
        aruco_params = cv2.aruco.DetectorParameters()
        detector     = cv2.aruco.ArucoDetector(aruco_dict, aruco_params)
    except AttributeError:
        print("  [!] ArUco requires opencv-contrib-python")
        print("      pip install opencv-contrib-python")
        return None, None

    img  = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    corners_all, ids, _ = detector.detectMarkers(gray)

    if ids is None or len(ids) == 0:
        print("  [!] No ArUco markers detected.")
        return None, None

    print(f"  ArUco markers detected: {len(ids)} (IDs: {ids.flatten()})")

    # Use first detected marker
    corners_2d = corners_all[0].reshape(-1,2)   # 4 x 2
    # OpenCV ArUco corner order is: top-left, top-right,
    # bottom-right, bottom-left (clockwise, as seen in image).
    # World points must follow the SAME order for correct pose.
    s = marker_cm
    world_pts = np.float32([
        [0, 0, 0],   # top-left
        [s, 0, 0],   # top-right
        [s, s, 0],   # bottom-right
        [0, s, 0],   # bottom-left
    ])

    cv2.aruco.drawDetectedMarkers(img, corners_all, ids)
    rvec, tvec = run_pnp(img, world_pts, corners_2d, K, D,
                   method=method, label="ArUco PnP")

    # ── measure additional object points using solved pose ─────
    if rvec is not None:
        obj_pts = object_pixel_pts
        if interactive_object:
            obj_pts = interactive_object_points(image_path)
        if obj_pts:
            measure_object_points(img, K, D, rvec, tvec, obj_pts)

    return rvec, tvec

# ── main ───────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Method B4: Perspective-n-Point (PnP)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)

    ap.add_argument("--demo",            action="store_true")
    ap.add_argument("--generate_marker", action="store_true")
    ap.add_argument("--checkerboard",    action="store_true")
    ap.add_argument("--aruco",           action="store_true")
    ap.add_argument("--manual",          action="store_true")
    ap.add_argument("--compare_solvers", action="store_true")

    ap.add_argument("--image",     default="images/method_b4_pnp/demo_scene.jpg")
    ap.add_argument("--calib",     default="calib_data.npz")
    ap.add_argument("--method",    default="epnp",
                    choices=["iterative","epnp","ippe"])
    ap.add_argument("--ransac",    action="store_true")

    ap.add_argument("--board_w",   type=int,   default=7)
    ap.add_argument("--board_h",   type=int,   default=5)
    ap.add_argument("--sq_cm",     type=float, default=2.5)
    ap.add_argument("--marker_cm", type=float, default=10.0)

    ap.add_argument("--world_pts", type=float, nargs="+",
                    help="3D world points: X1 Y1 Z1 X2 Y2 Z2 ...")
    ap.add_argument("--image_pts", type=float, nargs="+",
                    help="2D image points: u1 v1 u2 v2 ...")
    ap.add_argument("--object_pts", type=float, nargs="+", default=None,
                    help="Extra pixel points on the SAME plane to measure "
                         "(e.g. your object's endpoints): x1 y1 x2 y2 ...")
    ap.add_argument("--interactive_object", action="store_true",
                    help="Click object points on image instead of typing them")

    args = ap.parse_args()

    print("\n" + "═"*54)
    print("  METHOD B4 — Perspective-n-Point (PnP)")
    print("═"*54)

    # ── generate ArUco marker ─────────────────────────────────────
    if args.generate_marker:
        generate_aruco_marker()
        if not (args.demo or args.aruco or args.checkerboard or args.manual):
            return

    # ── demo mode ─────────────────────────────────────────────────
    if args.demo or not any([args.checkerboard, args.aruco, args.manual]):
        print("\n  Running demo with synthetic scene...")
        demo_path = "images/method_b4_pnp/demo_scene.jpg"
        img_demo, world_pts, img_pts, sq_cm = make_demo_scene(demo_path)

        K, D = load_or_default_calibration(
            args.calib, img_demo.shape)

        if args.compare_solvers:
            compare_all_solvers(img_demo, world_pts, img_pts, K, D)
        else:
            run_pnp(img_demo, world_pts, img_pts, K, D,
                    method=args.method,
                    use_ransac=args.ransac)
        print("\n  Demo complete. Check results/ folder.")
        return

    # ── load calibration ──────────────────────────────────────────
    img_tmp = cv2.imread(args.image)
    K, D = load_or_default_calibration(
        args.calib,
        img_tmp.shape if img_tmp is not None else None)

    # ── checkerboard mode ─────────────────────────────────────────
    if args.checkerboard:
        run_pnp_checkerboard(args.image, args.board_w, args.board_h,
                              args.sq_cm, K, D, args.method)

    # ── ArUco mode ────────────────────────────────────────────────
    elif args.aruco:
        obj_pixel_pts = None
        if args.object_pts:
            flat = args.object_pts
            obj_pixel_pts = [(flat[i], flat[i+1])
                              for i in range(0, len(flat)-1, 2)]
        run_pnp_aruco(args.image, args.marker_cm, K, D, args.method,
                      object_pixel_pts=obj_pixel_pts,
                      interactive_object=args.interactive_object)

    # ── manual correspondences ────────────────────────────────────
    elif args.manual:
        if not args.world_pts or not args.image_pts:
            print("  [!] Provide --world_pts and --image_pts")
            return

        w_flat = args.world_pts
        i_flat = args.image_pts

        world_pts = np.array(w_flat, dtype=np.float32).reshape(-1,3)
        img_pts   = np.array(i_flat, dtype=np.float32).reshape(-1,2)

        if len(world_pts) != len(img_pts):
            print(f"  [!] Points mismatch: "
                  f"{len(world_pts)} world vs {len(img_pts)} image")
            return

        img = cv2.imread(args.image)
        if img is None:
            img = np.ones((600,800,3),dtype=np.uint8)*200

        if args.compare_solvers:
            compare_all_solvers(img, world_pts, img_pts, K, D)
        else:
            rvec, tvec = run_pnp(img, world_pts, img_pts, K, D,
                    method=args.method, use_ransac=args.ransac)

            # ── measure additional object points on same plane ──────
            obj_pixel_pts = None
            if args.interactive_object:
                obj_pixel_pts = interactive_object_points(args.image)
            elif args.object_pts:
                flat = args.object_pts
                obj_pixel_pts = [(flat[i], flat[i+1])
                                  for i in range(0, len(flat)-1, 2)]

            if obj_pixel_pts and rvec is not None:
                measure_object_points(img, K, D, rvec, tvec, obj_pixel_pts)


if __name__ == "__main__":
    main()